---
- name: Building BE 
  hosts: all
  gather_facts: no
  become: yes
  become_user: build
  vars:
      work_dir: "/home/build/aayulogic"
      be_dir: "{{ work_dir }}/irealhrsoft-backend"
      python_dir: "{{ be_dir }}/realhrsoft/bin/python"
      git_dir: "/usr/bin/git"

  tasks:
      - name: Get current date
        command: date +"%d%m%Y"
        register: current_date
      - name:  make dir
        command: "mkdir test-awx chdir=/home/build"

        

       
       
       
  