---
- name: Build and Deploy Backend
  hosts: build
  connection: local
  gather_facts: no
  become: yes
  become_user: build

  vars:
    work_dir: "/home/build/aayulogic"
    be_dir: "{{ work_dir }}/irealhrsoft-backend"
    python_dir: "{{ be_dir }}/realhrsoft/bin/python"
    current_date: "{{ lookup('pipe', 'date +%d%m%Y') }}"

  tasks:

    - name: Clean old app-compile files and .7z archives
      ansible.builtin.find:
        paths: "{{ be_dir }}"
        patterns: ["app-compile", "*.7z"]
      register: old_files

    - name: Remove old app-compile and archive files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ old_files.files }}"
      when: old_files.matched > 0

    - name: Checkout target branch "{{ branch_name }}"
      ansible.builtin.command:
        cmd: "git checkout {{ branch_name }}"
      args:
        chdir: "{{ be_dir }}"

    - name: Pull latest changes for "{{ branch_name }}"
      ansible.builtin.command:
        cmd: "git pull origin {{ branch_name }}"
      args:
        chdir: "{{ be_dir }}"

    - name: Build app-compile 
      ansible.builtin.command:
        cmd: "{{ python_dir }} setup.py build_ext -j11 --inplace"
      args:
        chdir: "{{ be_dir }}"
    - command: "rm app_compile_{{ current_date }}.7z chdir={{ be_dir }}"
      ignore_errors: yes

    - name: Compress the app-compile folder 
      command: "/usr/bin/7z a app_compile_{{ current_date}}.7z app-compile chdir={{ be_dir }}"

    - name: Fetch the app_compile archive to local
      ansible.builtin.synchronize:
        src: "{{ be_dir }}/app_compile_{{ current_date }}.7z"
        dest: "/home/bimal/"
        mode: pull

    - name: Log build success
      ansible.builtin.debug:
        msg: "Build and archive successful for branch: {{ branch_name }} on {{ current_date }}"

